-- =============================================
-- Catálogo de figuritas FIFA World Cup 2026
-- Ejecutar en el SQL Editor de Supabase
-- =============================================

create table if not exists public.catalogo_figuritas (
  codigo text primary key,
  descripcion text not null,
  seccion text not null
);

alter table public.catalogo_figuritas enable row level security;

create policy "Catalogo publico" on public.catalogo_figuritas
  for select using (true);
-- Catálogo de figuritas FIFA World Cup 2026 Panini
-- Generado automáticamente - 980 figuritas

truncate table public.catalogo_figuritas;

insert into public.catalogo_figuritas (codigo, descripcion, seccion) values
  ('FWC1', 'Logo Panini (FOIL)', 'Apertura'),
  ('FWC2', 'Emblema Oficial (FOIL)', 'Apertura'),
  ('FWC3', 'Mascota Oficial (FOIL)', 'Apertura'),
  ('FWC4', 'Slogan Oficial (FOIL)', 'Apertura'),
  ('FWC5', 'Balón Oficial (FOIL)', 'Apertura'),
  ('FWC6', 'Sede - Estados Unidos (FOIL)', 'Apertura'),
  ('FWC7', 'Sede - Canadá (FOIL)', 'Apertura'),
  ('FWC8', 'Sede - México (FOIL)', 'Apertura'),
  ('FWC9', 'Cartel del Torneo (FOIL)', 'Apertura'),
  ('MUS1', 'Uruguay 1930 (FOIL)', 'FIFA Museum'),
  ('MUS2', 'Italia 1934 & 1938 (FOIL)', 'FIFA Museum'),
  ('MUS3', 'Brasil 1958 & 1962 (FOIL)', 'FIFA Museum'),
  ('MUS4', 'Inglaterra 1966 (FOIL)', 'FIFA Museum'),
  ('MUS5', 'Brasil 1970 (FOIL)', 'FIFA Museum'),
  ('MUS6', 'Alemania 1974 (FOIL)', 'FIFA Museum'),
  ('MUS7', 'Argentina 1978 & 1986 (FOIL)', 'FIFA Museum'),
  ('MUS8', 'Italia 1982 & 2006 (FOIL)', 'FIFA Museum'),
  ('MUS9', 'Alemania 1990 & 2014 (FOIL)', 'FIFA Museum'),
  ('MUS10', 'Brasil 1994 (FOIL)', 'FIFA Museum'),
  ('MUS11', 'Francia 1998 & 2018 (FOIL)', 'FIFA Museum'),
  ('ALG1', 'Algeria - Escudo (FOIL)', 'Algeria'),
  ('ALG2', 'Algeria - Jugador', 'Algeria'),
  ('ALG3', 'Algeria - Jugador', 'Algeria'),
  ('ALG4', 'Algeria - Jugador', 'Algeria'),
  ('ALG5', 'Algeria - Jugador', 'Algeria'),
  ('ALG6', 'Algeria - Jugador', 'Algeria'),
  ('ALG7', 'Algeria - Jugador', 'Algeria'),
  ('ALG8', 'Algeria - Jugador', 'Algeria'),
  ('ALG9', 'Algeria - Jugador', 'Algeria'),
  ('ALG10', 'Algeria - Jugador', 'Algeria'),
  ('ALG11', 'Algeria - Jugador', 'Algeria'),
  ('ALG12', 'Algeria - Jugador', 'Algeria'),
  ('ALG13', 'Algeria - Foto del equipo', 'Algeria'),
  ('ALG14', 'Algeria - Jugador', 'Algeria'),
  ('ALG15', 'Algeria - Jugador', 'Algeria'),
  ('ALG16', 'Algeria - Jugador', 'Algeria'),
  ('ALG17', 'Algeria - Jugador', 'Algeria'),
  ('ALG18', 'Algeria - Jugador', 'Algeria'),
  ('ALG19', 'Algeria - Jugador', 'Algeria'),
  ('ALG20', 'Algeria - Jugador', 'Algeria'),
  ('ARG1', 'Argentina - Escudo (FOIL)', 'Argentina'),
  ('ARG2', 'Argentina - Jugador', 'Argentina'),
  ('ARG3', 'Argentina - Jugador', 'Argentina'),
  ('ARG4', 'Argentina - Jugador', 'Argentina'),
  ('ARG5', 'Argentina - Jugador', 'Argentina'),
  ('ARG6', 'Argentina - Jugador', 'Argentina'),
  ('ARG7', 'Argentina - Jugador', 'Argentina'),
  ('ARG8', 'Argentina - Jugador', 'Argentina'),
  ('ARG9', 'Argentina - Jugador', 'Argentina'),
  ('ARG10', 'Argentina - Jugador', 'Argentina'),
  ('ARG11', 'Argentina - Jugador', 'Argentina'),
  ('ARG12', 'Argentina - Jugador', 'Argentina'),
  ('ARG13', 'Argentina - Foto del equipo', 'Argentina'),
  ('ARG14', 'Argentina - Jugador', 'Argentina'),
  ('ARG15', 'Argentina - Jugador', 'Argentina'),
  ('ARG16', 'Argentina - Jugador', 'Argentina'),
  ('ARG17', 'Argentina - Jugador', 'Argentina'),
  ('ARG18', 'Argentina - Jugador', 'Argentina'),
  ('ARG19', 'Argentina - Jugador', 'Argentina'),
  ('ARG20', 'Argentina - Jugador', 'Argentina'),
  ('AUS1', 'Australia - Escudo (FOIL)', 'Australia'),
  ('AUS2', 'Australia - Jugador', 'Australia'),
  ('AUS3', 'Australia - Jugador', 'Australia'),
  ('AUS4', 'Australia - Jugador', 'Australia'),
  ('AUS5', 'Australia - Jugador', 'Australia'),
  ('AUS6', 'Australia - Jugador', 'Australia'),
  ('AUS7', 'Australia - Jugador', 'Australia'),
  ('AUS8', 'Australia - Jugador', 'Australia'),
  ('AUS9', 'Australia - Jugador', 'Australia'),
  ('AUS10', 'Australia - Jugador', 'Australia'),
  ('AUS11', 'Australia - Jugador', 'Australia'),
  ('AUS12', 'Australia - Jugador', 'Australia'),
  ('AUS13', 'Australia - Foto del equipo', 'Australia'),
  ('AUS14', 'Australia - Jugador', 'Australia'),
  ('AUS15', 'Australia - Jugador', 'Australia'),
  ('AUS16', 'Australia - Jugador', 'Australia'),
  ('AUS17', 'Australia - Jugador', 'Australia'),
  ('AUS18', 'Australia - Jugador', 'Australia'),
  ('AUS19', 'Australia - Jugador', 'Australia'),
  ('AUS20', 'Australia - Jugador', 'Australia'),
  ('AUT1', 'Austria - Escudo (FOIL)', 'Austria'),
  ('AUT2', 'Austria - Jugador', 'Austria'),
  ('AUT3', 'Austria - Jugador', 'Austria'),
  ('AUT4', 'Austria - Jugador', 'Austria'),
  ('AUT5', 'Austria - Jugador', 'Austria'),
  ('AUT6', 'Austria - Jugador', 'Austria'),
  ('AUT7', 'Austria - Jugador', 'Austria'),
  ('AUT8', 'Austria - Jugador', 'Austria'),
  ('AUT9', 'Austria - Jugador', 'Austria'),
  ('AUT10', 'Austria - Jugador', 'Austria'),
  ('AUT11', 'Austria - Jugador', 'Austria'),
  ('AUT12', 'Austria - Jugador', 'Austria'),
  ('AUT13', 'Austria - Foto del equipo', 'Austria'),
  ('AUT14', 'Austria - Jugador', 'Austria'),
  ('AUT15', 'Austria - Jugador', 'Austria'),
  ('AUT16', 'Austria - Jugador', 'Austria'),
  ('AUT17', 'Austria - Jugador', 'Austria'),
  ('AUT18', 'Austria - Jugador', 'Austria'),
  ('AUT19', 'Austria - Jugador', 'Austria'),
  ('AUT20', 'Austria - Jugador', 'Austria'),
  ('BEL1', 'Bélgica - Escudo (FOIL)', 'Bélgica'),
  ('BEL2', 'Bélgica - Jugador', 'Bélgica'),
  ('BEL3', 'Bélgica - Jugador', 'Bélgica'),
  ('BEL4', 'Bélgica - Jugador', 'Bélgica'),
  ('BEL5', 'Bélgica - Jugador', 'Bélgica'),
  ('BEL6', 'Bélgica - Jugador', 'Bélgica'),
  ('BEL7', 'Bélgica - Jugador', 'Bélgica'),
  ('BEL8', 'Bélgica - Jugador', 'Bélgica'),
  ('BEL9', 'Bélgica - Jugador', 'Bélgica'),
  ('BEL10', 'Bélgica - Jugador', 'Bélgica'),
  ('BEL11', 'Bélgica - Jugador', 'Bélgica'),
  ('BEL12', 'Bélgica - Jugador', 'Bélgica'),
  ('BEL13', 'Bélgica - Foto del equipo', 'Bélgica'),
  ('BEL14', 'Bélgica - Jugador', 'Bélgica'),
  ('BEL15', 'Bélgica - Jugador', 'Bélgica'),
  ('BEL16', 'Bélgica - Jugador', 'Bélgica'),
  ('BEL17', 'Bélgica - Jugador', 'Bélgica'),
  ('BEL18', 'Bélgica - Jugador', 'Bélgica'),
  ('BEL19', 'Bélgica - Jugador', 'Bélgica'),
  ('BEL20', 'Bélgica - Jugador', 'Bélgica'),
  ('BIH1', 'Bosnia y Herzegovina - Escudo (FOIL)', 'Bosnia y Herzegovina'),
  ('BIH2', 'Bosnia y Herzegovina - Jugador', 'Bosnia y Herzegovina'),
  ('BIH3', 'Bosnia y Herzegovina - Jugador', 'Bosnia y Herzegovina'),
  ('BIH4', 'Bosnia y Herzegovina - Jugador', 'Bosnia y Herzegovina'),
  ('BIH5', 'Bosnia y Herzegovina - Jugador', 'Bosnia y Herzegovina'),
  ('BIH6', 'Bosnia y Herzegovina - Jugador', 'Bosnia y Herzegovina'),
  ('BIH7', 'Bosnia y Herzegovina - Jugador', 'Bosnia y Herzegovina'),
  ('BIH8', 'Bosnia y Herzegovina - Jugador', 'Bosnia y Herzegovina'),
  ('BIH9', 'Bosnia y Herzegovina - Jugador', 'Bosnia y Herzegovina'),
  ('BIH10', 'Bosnia y Herzegovina - Jugador', 'Bosnia y Herzegovina'),
  ('BIH11', 'Bosnia y Herzegovina - Jugador', 'Bosnia y Herzegovina'),
  ('BIH12', 'Bosnia y Herzegovina - Jugador', 'Bosnia y Herzegovina'),
  ('BIH13', 'Bosnia y Herzegovina - Foto del equipo', 'Bosnia y Herzegovina'),
  ('BIH14', 'Bosnia y Herzegovina - Jugador', 'Bosnia y Herzegovina'),
  ('BIH15', 'Bosnia y Herzegovina - Jugador', 'Bosnia y Herzegovina'),
  ('BIH16', 'Bosnia y Herzegovina - Jugador', 'Bosnia y Herzegovina'),
  ('BIH17', 'Bosnia y Herzegovina - Jugador', 'Bosnia y Herzegovina'),
  ('BIH18', 'Bosnia y Herzegovina - Jugador', 'Bosnia y Herzegovina'),
  ('BIH19', 'Bosnia y Herzegovina - Jugador', 'Bosnia y Herzegovina'),
  ('BIH20', 'Bosnia y Herzegovina - Jugador', 'Bosnia y Herzegovina'),
  ('BRA1', 'Brasil - Escudo (FOIL)', 'Brasil'),
  ('BRA2', 'Brasil - Jugador', 'Brasil'),
  ('BRA3', 'Brasil - Jugador', 'Brasil'),
  ('BRA4', 'Brasil - Jugador', 'Brasil'),
  ('BRA5', 'Brasil - Jugador', 'Brasil'),
  ('BRA6', 'Brasil - Jugador', 'Brasil'),
  ('BRA7', 'Brasil - Jugador', 'Brasil'),
  ('BRA8', 'Brasil - Jugador', 'Brasil'),
  ('BRA9', 'Brasil - Jugador', 'Brasil'),
  ('BRA10', 'Brasil - Jugador', 'Brasil'),
  ('BRA11', 'Brasil - Jugador', 'Brasil'),
  ('BRA12', 'Brasil - Jugador', 'Brasil'),
  ('BRA13', 'Brasil - Foto del equipo', 'Brasil'),
  ('BRA14', 'Brasil - Jugador', 'Brasil'),
  ('BRA15', 'Brasil - Jugador', 'Brasil'),
  ('BRA16', 'Brasil - Jugador', 'Brasil'),
  ('BRA17', 'Brasil - Jugador', 'Brasil'),
  ('BRA18', 'Brasil - Jugador', 'Brasil'),
  ('BRA19', 'Brasil - Jugador', 'Brasil'),
  ('BRA20', 'Brasil - Jugador', 'Brasil'),
  ('CAN1', 'Canadá - Escudo (FOIL)', 'Canadá'),
  ('CAN2', 'Canadá - Jugador', 'Canadá'),
  ('CAN3', 'Canadá - Jugador', 'Canadá'),
  ('CAN4', 'Canadá - Jugador', 'Canadá'),
  ('CAN5', 'Canadá - Jugador', 'Canadá'),
  ('CAN6', 'Canadá - Jugador', 'Canadá'),
  ('CAN7', 'Canadá - Jugador', 'Canadá'),
  ('CAN8', 'Canadá - Jugador', 'Canadá'),
  ('CAN9', 'Canadá - Jugador', 'Canadá'),
  ('CAN10', 'Canadá - Jugador', 'Canadá'),
  ('CAN11', 'Canadá - Jugador', 'Canadá'),
  ('CAN12', 'Canadá - Jugador', 'Canadá'),
  ('CAN13', 'Canadá - Foto del equipo', 'Canadá'),
  ('CAN14', 'Canadá - Jugador', 'Canadá'),
  ('CAN15', 'Canadá - Jugador', 'Canadá'),
  ('CAN16', 'Canadá - Jugador', 'Canadá'),
  ('CAN17', 'Canadá - Jugador', 'Canadá'),
  ('CAN18', 'Canadá - Jugador', 'Canadá'),
  ('CAN19', 'Canadá - Jugador', 'Canadá'),
  ('CAN20', 'Canadá - Jugador', 'Canadá'),
  ('CIV1', 'Costa de Marfil - Escudo (FOIL)', 'Costa de Marfil'),
  ('CIV2', 'Costa de Marfil - Jugador', 'Costa de Marfil'),
  ('CIV3', 'Costa de Marfil - Jugador', 'Costa de Marfil'),
  ('CIV4', 'Costa de Marfil - Jugador', 'Costa de Marfil'),
  ('CIV5', 'Costa de Marfil - Jugador', 'Costa de Marfil'),
  ('CIV6', 'Costa de Marfil - Jugador', 'Costa de Marfil'),
  ('CIV7', 'Costa de Marfil - Jugador', 'Costa de Marfil'),
  ('CIV8', 'Costa de Marfil - Jugador', 'Costa de Marfil'),
  ('CIV9', 'Costa de Marfil - Jugador', 'Costa de Marfil'),
  ('CIV10', 'Costa de Marfil - Jugador', 'Costa de Marfil'),
  ('CIV11', 'Costa de Marfil - Jugador', 'Costa de Marfil'),
  ('CIV12', 'Costa de Marfil - Jugador', 'Costa de Marfil'),
  ('CIV13', 'Costa de Marfil - Foto del equipo', 'Costa de Marfil'),
  ('CIV14', 'Costa de Marfil - Jugador', 'Costa de Marfil'),
  ('CIV15', 'Costa de Marfil - Jugador', 'Costa de Marfil'),
  ('CIV16', 'Costa de Marfil - Jugador', 'Costa de Marfil'),
  ('CIV17', 'Costa de Marfil - Jugador', 'Costa de Marfil'),
  ('CIV18', 'Costa de Marfil - Jugador', 'Costa de Marfil'),
  ('CIV19', 'Costa de Marfil - Jugador', 'Costa de Marfil'),
  ('CIV20', 'Costa de Marfil - Jugador', 'Costa de Marfil'),
  ('COD1', 'Congo DR - Escudo (FOIL)', 'Congo DR'),
  ('COD2', 'Congo DR - Jugador', 'Congo DR'),
  ('COD3', 'Congo DR - Jugador', 'Congo DR'),
  ('COD4', 'Congo DR - Jugador', 'Congo DR'),
  ('COD5', 'Congo DR - Jugador', 'Congo DR'),
  ('COD6', 'Congo DR - Jugador', 'Congo DR'),
  ('COD7', 'Congo DR - Jugador', 'Congo DR'),
  ('COD8', 'Congo DR - Jugador', 'Congo DR'),
  ('COD9', 'Congo DR - Jugador', 'Congo DR'),
  ('COD10', 'Congo DR - Jugador', 'Congo DR'),
  ('COD11', 'Congo DR - Jugador', 'Congo DR'),
  ('COD12', 'Congo DR - Jugador', 'Congo DR'),
  ('COD13', 'Congo DR - Foto del equipo', 'Congo DR'),
  ('COD14', 'Congo DR - Jugador', 'Congo DR'),
  ('COD15', 'Congo DR - Jugador', 'Congo DR'),
  ('COD16', 'Congo DR - Jugador', 'Congo DR'),
  ('COD17', 'Congo DR - Jugador', 'Congo DR'),
  ('COD18', 'Congo DR - Jugador', 'Congo DR'),
  ('COD19', 'Congo DR - Jugador', 'Congo DR'),
  ('COD20', 'Congo DR - Jugador', 'Congo DR'),
  ('COL1', 'Colombia - Escudo (FOIL)', 'Colombia'),
  ('COL2', 'Colombia - Jugador', 'Colombia'),
  ('COL3', 'Colombia - Jugador', 'Colombia'),
  ('COL4', 'Colombia - Jugador', 'Colombia'),
  ('COL5', 'Colombia - Jugador', 'Colombia'),
  ('COL6', 'Colombia - Jugador', 'Colombia'),
  ('COL7', 'Colombia - Jugador', 'Colombia'),
  ('COL8', 'Colombia - Jugador', 'Colombia'),
  ('COL9', 'Colombia - Jugador', 'Colombia'),
  ('COL10', 'Colombia - Jugador', 'Colombia'),
  ('COL11', 'Colombia - Jugador', 'Colombia'),
  ('COL12', 'Colombia - Jugador', 'Colombia'),
  ('COL13', 'Colombia - Foto del equipo', 'Colombia'),
  ('COL14', 'Colombia - Jugador', 'Colombia'),
  ('COL15', 'Colombia - Jugador', 'Colombia'),
  ('COL16', 'Colombia - Jugador', 'Colombia'),
  ('COL17', 'Colombia - Jugador', 'Colombia'),
  ('COL18', 'Colombia - Jugador', 'Colombia'),
  ('COL19', 'Colombia - Jugador', 'Colombia'),
  ('COL20', 'Colombia - Jugador', 'Colombia'),
  ('CPV1', 'Cabo Verde - Escudo (FOIL)', 'Cabo Verde'),
  ('CPV2', 'Cabo Verde - Jugador', 'Cabo Verde'),
  ('CPV3', 'Cabo Verde - Jugador', 'Cabo Verde'),
  ('CPV4', 'Cabo Verde - Jugador', 'Cabo Verde'),
  ('CPV5', 'Cabo Verde - Jugador', 'Cabo Verde'),
  ('CPV6', 'Cabo Verde - Jugador', 'Cabo Verde'),
  ('CPV7', 'Cabo Verde - Jugador', 'Cabo Verde'),
  ('CPV8', 'Cabo Verde - Jugador', 'Cabo Verde'),
  ('CPV9', 'Cabo Verde - Jugador', 'Cabo Verde'),
  ('CPV10', 'Cabo Verde - Jugador', 'Cabo Verde'),
  ('CPV11', 'Cabo Verde - Jugador', 'Cabo Verde'),
  ('CPV12', 'Cabo Verde - Jugador', 'Cabo Verde'),
  ('CPV13', 'Cabo Verde - Foto del equipo', 'Cabo Verde'),
  ('CPV14', 'Cabo Verde - Jugador', 'Cabo Verde'),
  ('CPV15', 'Cabo Verde - Jugador', 'Cabo Verde'),
  ('CPV16', 'Cabo Verde - Jugador', 'Cabo Verde'),
  ('CPV17', 'Cabo Verde - Jugador', 'Cabo Verde'),
  ('CPV18', 'Cabo Verde - Jugador', 'Cabo Verde'),
  ('CPV19', 'Cabo Verde - Jugador', 'Cabo Verde'),
  ('CPV20', 'Cabo Verde - Jugador', 'Cabo Verde'),
  ('CRO1', 'Croacia - Escudo (FOIL)', 'Croacia'),
  ('CRO2', 'Croacia - Jugador', 'Croacia'),
  ('CRO3', 'Croacia - Jugador', 'Croacia'),
  ('CRO4', 'Croacia - Jugador', 'Croacia'),
  ('CRO5', 'Croacia - Jugador', 'Croacia'),
  ('CRO6', 'Croacia - Jugador', 'Croacia'),
  ('CRO7', 'Croacia - Jugador', 'Croacia'),
  ('CRO8', 'Croacia - Jugador', 'Croacia'),
  ('CRO9', 'Croacia - Jugador', 'Croacia'),
  ('CRO10', 'Croacia - Jugador', 'Croacia'),
  ('CRO11', 'Croacia - Jugador', 'Croacia'),
  ('CRO12', 'Croacia - Jugador', 'Croacia'),
  ('CRO13', 'Croacia - Foto del equipo', 'Croacia'),
  ('CRO14', 'Croacia - Jugador', 'Croacia'),
  ('CRO15', 'Croacia - Jugador', 'Croacia'),
  ('CRO16', 'Croacia - Jugador', 'Croacia'),
  ('CRO17', 'Croacia - Jugador', 'Croacia'),
  ('CRO18', 'Croacia - Jugador', 'Croacia'),
  ('CRO19', 'Croacia - Jugador', 'Croacia'),
  ('CRO20', 'Croacia - Jugador', 'Croacia'),
  ('CUW1', 'Curaçao - Escudo (FOIL)', 'Curaçao'),
  ('CUW2', 'Curaçao - Jugador', 'Curaçao'),
  ('CUW3', 'Curaçao - Jugador', 'Curaçao'),
  ('CUW4', 'Curaçao - Jugador', 'Curaçao'),
  ('CUW5', 'Curaçao - Jugador', 'Curaçao'),
  ('CUW6', 'Curaçao - Jugador', 'Curaçao'),
  ('CUW7', 'Curaçao - Jugador', 'Curaçao'),
  ('CUW8', 'Curaçao - Jugador', 'Curaçao'),
  ('CUW9', 'Curaçao - Jugador', 'Curaçao'),
  ('CUW10', 'Curaçao - Jugador', 'Curaçao'),
  ('CUW11', 'Curaçao - Jugador', 'Curaçao'),
  ('CUW12', 'Curaçao - Jugador', 'Curaçao'),
  ('CUW13', 'Curaçao - Foto del equipo', 'Curaçao'),
  ('CUW14', 'Curaçao - Jugador', 'Curaçao'),
  ('CUW15', 'Curaçao - Jugador', 'Curaçao'),
  ('CUW16', 'Curaçao - Jugador', 'Curaçao'),
  ('CUW17', 'Curaçao - Jugador', 'Curaçao'),
  ('CUW18', 'Curaçao - Jugador', 'Curaçao'),
  ('CUW19', 'Curaçao - Jugador', 'Curaçao'),
  ('CUW20', 'Curaçao - Jugador', 'Curaçao'),
  ('CZE1', 'República Checa - Escudo (FOIL)', 'República Checa'),
  ('CZE2', 'República Checa - Jugador', 'República Checa'),
  ('CZE3', 'República Checa - Jugador', 'República Checa'),
  ('CZE4', 'República Checa - Jugador', 'República Checa'),
  ('CZE5', 'República Checa - Jugador', 'República Checa'),
  ('CZE6', 'República Checa - Jugador', 'República Checa'),
  ('CZE7', 'República Checa - Jugador', 'República Checa'),
  ('CZE8', 'República Checa - Jugador', 'República Checa'),
  ('CZE9', 'República Checa - Jugador', 'República Checa'),
  ('CZE10', 'República Checa - Jugador', 'República Checa'),
  ('CZE11', 'República Checa - Jugador', 'República Checa'),
  ('CZE12', 'República Checa - Jugador', 'República Checa'),
  ('CZE13', 'República Checa - Foto del equipo', 'República Checa'),
  ('CZE14', 'República Checa - Jugador', 'República Checa'),
  ('CZE15', 'República Checa - Jugador', 'República Checa'),
  ('CZE16', 'República Checa - Jugador', 'República Checa'),
  ('CZE17', 'República Checa - Jugador', 'República Checa'),
  ('CZE18', 'República Checa - Jugador', 'República Checa'),
  ('CZE19', 'República Checa - Jugador', 'República Checa'),
  ('CZE20', 'República Checa - Jugador', 'República Checa'),
  ('ECU1', 'Ecuador - Escudo (FOIL)', 'Ecuador'),
  ('ECU2', 'Ecuador - Jugador', 'Ecuador'),
  ('ECU3', 'Ecuador - Jugador', 'Ecuador'),
  ('ECU4', 'Ecuador - Jugador', 'Ecuador'),
  ('ECU5', 'Ecuador - Jugador', 'Ecuador'),
  ('ECU6', 'Ecuador - Jugador', 'Ecuador'),
  ('ECU7', 'Ecuador - Jugador', 'Ecuador'),
  ('ECU8', 'Ecuador - Jugador', 'Ecuador'),
  ('ECU9', 'Ecuador - Jugador', 'Ecuador'),
  ('ECU10', 'Ecuador - Jugador', 'Ecuador'),
  ('ECU11', 'Ecuador - Jugador', 'Ecuador'),
  ('ECU12', 'Ecuador - Jugador', 'Ecuador'),
  ('ECU13', 'Ecuador - Foto del equipo', 'Ecuador'),
  ('ECU14', 'Ecuador - Jugador', 'Ecuador'),
  ('ECU15', 'Ecuador - Jugador', 'Ecuador'),
  ('ECU16', 'Ecuador - Jugador', 'Ecuador'),
  ('ECU17', 'Ecuador - Jugador', 'Ecuador'),
  ('ECU18', 'Ecuador - Jugador', 'Ecuador'),
  ('ECU19', 'Ecuador - Jugador', 'Ecuador'),
  ('ECU20', 'Ecuador - Jugador', 'Ecuador'),
  ('EGY1', 'Egipto - Escudo (FOIL)', 'Egipto'),
  ('EGY2', 'Egipto - Jugador', 'Egipto'),
  ('EGY3', 'Egipto - Jugador', 'Egipto'),
  ('EGY4', 'Egipto - Jugador', 'Egipto'),
  ('EGY5', 'Egipto - Jugador', 'Egipto'),
  ('EGY6', 'Egipto - Jugador', 'Egipto'),
  ('EGY7', 'Egipto - Jugador', 'Egipto'),
  ('EGY8', 'Egipto - Jugador', 'Egipto'),
  ('EGY9', 'Egipto - Jugador', 'Egipto'),
  ('EGY10', 'Egipto - Jugador', 'Egipto'),
  ('EGY11', 'Egipto - Jugador', 'Egipto'),
  ('EGY12', 'Egipto - Jugador', 'Egipto'),
  ('EGY13', 'Egipto - Foto del equipo', 'Egipto'),
  ('EGY14', 'Egipto - Jugador', 'Egipto'),
  ('EGY15', 'Egipto - Jugador', 'Egipto'),
  ('EGY16', 'Egipto - Jugador', 'Egipto'),
  ('EGY17', 'Egipto - Jugador', 'Egipto'),
  ('EGY18', 'Egipto - Jugador', 'Egipto'),
  ('EGY19', 'Egipto - Jugador', 'Egipto'),
  ('EGY20', 'Egipto - Jugador', 'Egipto'),
  ('ENG1', 'Inglaterra - Escudo (FOIL)', 'Inglaterra'),
  ('ENG2', 'Inglaterra - Jugador', 'Inglaterra'),
  ('ENG3', 'Inglaterra - Jugador', 'Inglaterra'),
  ('ENG4', 'Inglaterra - Jugador', 'Inglaterra'),
  ('ENG5', 'Inglaterra - Jugador', 'Inglaterra'),
  ('ENG6', 'Inglaterra - Jugador', 'Inglaterra'),
  ('ENG7', 'Inglaterra - Jugador', 'Inglaterra'),
  ('ENG8', 'Inglaterra - Jugador', 'Inglaterra'),
  ('ENG9', 'Inglaterra - Jugador', 'Inglaterra'),
  ('ENG10', 'Inglaterra - Jugador', 'Inglaterra'),
  ('ENG11', 'Inglaterra - Jugador', 'Inglaterra'),
  ('ENG12', 'Inglaterra - Jugador', 'Inglaterra'),
  ('ENG13', 'Inglaterra - Foto del equipo', 'Inglaterra'),
  ('ENG14', 'Inglaterra - Jugador', 'Inglaterra'),
  ('ENG15', 'Inglaterra - Jugador', 'Inglaterra'),
  ('ENG16', 'Inglaterra - Jugador', 'Inglaterra'),
  ('ENG17', 'Inglaterra - Jugador', 'Inglaterra'),
  ('ENG18', 'Inglaterra - Jugador', 'Inglaterra'),
  ('ENG19', 'Inglaterra - Jugador', 'Inglaterra'),
  ('ENG20', 'Inglaterra - Jugador', 'Inglaterra'),
  ('ESP1', 'España - Escudo (FOIL)', 'España'),
  ('ESP2', 'España - Jugador', 'España'),
  ('ESP3', 'España - Jugador', 'España'),
  ('ESP4', 'España - Jugador', 'España'),
  ('ESP5', 'España - Jugador', 'España'),
  ('ESP6', 'España - Jugador', 'España'),
  ('ESP7', 'España - Jugador', 'España'),
  ('ESP8', 'España - Jugador', 'España'),
  ('ESP9', 'España - Jugador', 'España'),
  ('ESP10', 'España - Jugador', 'España'),
  ('ESP11', 'España - Jugador', 'España'),
  ('ESP12', 'España - Jugador', 'España'),
  ('ESP13', 'España - Foto del equipo', 'España'),
  ('ESP14', 'España - Jugador', 'España'),
  ('ESP15', 'España - Jugador', 'España'),
  ('ESP16', 'España - Jugador', 'España'),
  ('ESP17', 'España - Jugador', 'España'),
  ('ESP18', 'España - Jugador', 'España'),
  ('ESP19', 'España - Jugador', 'España'),
  ('ESP20', 'España - Jugador', 'España'),
  ('FRA1', 'Francia - Escudo (FOIL)', 'Francia'),
  ('FRA2', 'Francia - Jugador', 'Francia'),
  ('FRA3', 'Francia - Jugador', 'Francia'),
  ('FRA4', 'Francia - Jugador', 'Francia'),
  ('FRA5', 'Francia - Jugador', 'Francia'),
  ('FRA6', 'Francia - Jugador', 'Francia'),
  ('FRA7', 'Francia - Jugador', 'Francia'),
  ('FRA8', 'Francia - Jugador', 'Francia'),
  ('FRA9', 'Francia - Jugador', 'Francia'),
  ('FRA10', 'Francia - Jugador', 'Francia'),
  ('FRA11', 'Francia - Jugador', 'Francia'),
  ('FRA12', 'Francia - Jugador', 'Francia'),
  ('FRA13', 'Francia - Foto del equipo', 'Francia'),
  ('FRA14', 'Francia - Jugador', 'Francia'),
  ('FRA15', 'Francia - Jugador', 'Francia'),
  ('FRA16', 'Francia - Jugador', 'Francia'),
  ('FRA17', 'Francia - Jugador', 'Francia'),
  ('FRA18', 'Francia - Jugador', 'Francia'),
  ('FRA19', 'Francia - Jugador', 'Francia'),
  ('FRA20', 'Francia - Jugador', 'Francia'),
  ('GER1', 'Alemania - Escudo (FOIL)', 'Alemania'),
  ('GER2', 'Alemania - Jugador', 'Alemania'),
  ('GER3', 'Alemania - Jugador', 'Alemania'),
  ('GER4', 'Alemania - Jugador', 'Alemania'),
  ('GER5', 'Alemania - Jugador', 'Alemania'),
  ('GER6', 'Alemania - Jugador', 'Alemania'),
  ('GER7', 'Alemania - Jugador', 'Alemania'),
  ('GER8', 'Alemania - Jugador', 'Alemania'),
  ('GER9', 'Alemania - Jugador', 'Alemania'),
  ('GER10', 'Alemania - Jugador', 'Alemania'),
  ('GER11', 'Alemania - Jugador', 'Alemania'),
  ('GER12', 'Alemania - Jugador', 'Alemania'),
  ('GER13', 'Alemania - Foto del equipo', 'Alemania'),
  ('GER14', 'Alemania - Jugador', 'Alemania'),
  ('GER15', 'Alemania - Jugador', 'Alemania'),
  ('GER16', 'Alemania - Jugador', 'Alemania'),
  ('GER17', 'Alemania - Jugador', 'Alemania'),
  ('GER18', 'Alemania - Jugador', 'Alemania'),
  ('GER19', 'Alemania - Jugador', 'Alemania'),
  ('GER20', 'Alemania - Jugador', 'Alemania'),
  ('GHA1', 'Ghana - Escudo (FOIL)', 'Ghana'),
  ('GHA2', 'Ghana - Jugador', 'Ghana'),
  ('GHA3', 'Ghana - Jugador', 'Ghana'),
  ('GHA4', 'Ghana - Jugador', 'Ghana'),
  ('GHA5', 'Ghana - Jugador', 'Ghana'),
  ('GHA6', 'Ghana - Jugador', 'Ghana'),
  ('GHA7', 'Ghana - Jugador', 'Ghana'),
  ('GHA8', 'Ghana - Jugador', 'Ghana'),
  ('GHA9', 'Ghana - Jugador', 'Ghana'),
  ('GHA10', 'Ghana - Jugador', 'Ghana'),
  ('GHA11', 'Ghana - Jugador', 'Ghana'),
  ('GHA12', 'Ghana - Jugador', 'Ghana'),
  ('GHA13', 'Ghana - Foto del equipo', 'Ghana'),
  ('GHA14', 'Ghana - Jugador', 'Ghana'),
  ('GHA15', 'Ghana - Jugador', 'Ghana'),
  ('GHA16', 'Ghana - Jugador', 'Ghana'),
  ('GHA17', 'Ghana - Jugador', 'Ghana'),
  ('GHA18', 'Ghana - Jugador', 'Ghana'),
  ('GHA19', 'Ghana - Jugador', 'Ghana'),
  ('GHA20', 'Ghana - Jugador', 'Ghana'),
  ('HAI1', 'Haití - Escudo (FOIL)', 'Haití'),
  ('HAI2', 'Haití - Jugador', 'Haití'),
  ('HAI3', 'Haití - Jugador', 'Haití'),
  ('HAI4', 'Haití - Jugador', 'Haití'),
  ('HAI5', 'Haití - Jugador', 'Haití'),
  ('HAI6', 'Haití - Jugador', 'Haití'),
  ('HAI7', 'Haití - Jugador', 'Haití'),
  ('HAI8', 'Haití - Jugador', 'Haití'),
  ('HAI9', 'Haití - Jugador', 'Haití'),
  ('HAI10', 'Haití - Jugador', 'Haití'),
  ('HAI11', 'Haití - Jugador', 'Haití'),
  ('HAI12', 'Haití - Jugador', 'Haití'),
  ('HAI13', 'Haití - Foto del equipo', 'Haití'),
  ('HAI14', 'Haití - Jugador', 'Haití'),
  ('HAI15', 'Haití - Jugador', 'Haití'),
  ('HAI16', 'Haití - Jugador', 'Haití'),
  ('HAI17', 'Haití - Jugador', 'Haití'),
  ('HAI18', 'Haití - Jugador', 'Haití'),
  ('HAI19', 'Haití - Jugador', 'Haití'),
  ('HAI20', 'Haití - Jugador', 'Haití'),
  ('IRN1', 'Irán - Escudo (FOIL)', 'Irán'),
  ('IRN2', 'Irán - Jugador', 'Irán'),
  ('IRN3', 'Irán - Jugador', 'Irán'),
  ('IRN4', 'Irán - Jugador', 'Irán'),
  ('IRN5', 'Irán - Jugador', 'Irán'),
  ('IRN6', 'Irán - Jugador', 'Irán'),
  ('IRN7', 'Irán - Jugador', 'Irán'),
  ('IRN8', 'Irán - Jugador', 'Irán'),
  ('IRN9', 'Irán - Jugador', 'Irán'),
  ('IRN10', 'Irán - Jugador', 'Irán'),
  ('IRN11', 'Irán - Jugador', 'Irán'),
  ('IRN12', 'Irán - Jugador', 'Irán'),
  ('IRN13', 'Irán - Foto del equipo', 'Irán'),
  ('IRN14', 'Irán - Jugador', 'Irán'),
  ('IRN15', 'Irán - Jugador', 'Irán'),
  ('IRN16', 'Irán - Jugador', 'Irán'),
  ('IRN17', 'Irán - Jugador', 'Irán'),
  ('IRN18', 'Irán - Jugador', 'Irán'),
  ('IRN19', 'Irán - Jugador', 'Irán'),
  ('IRN20', 'Irán - Jugador', 'Irán'),
  ('IRQ1', 'Irak - Escudo (FOIL)', 'Irak'),
  ('IRQ2', 'Irak - Jugador', 'Irak'),
  ('IRQ3', 'Irak - Jugador', 'Irak'),
  ('IRQ4', 'Irak - Jugador', 'Irak'),
  ('IRQ5', 'Irak - Jugador', 'Irak'),
  ('IRQ6', 'Irak - Jugador', 'Irak'),
  ('IRQ7', 'Irak - Jugador', 'Irak'),
  ('IRQ8', 'Irak - Jugador', 'Irak'),
  ('IRQ9', 'Irak - Jugador', 'Irak'),
  ('IRQ10', 'Irak - Jugador', 'Irak'),
  ('IRQ11', 'Irak - Jugador', 'Irak'),
  ('IRQ12', 'Irak - Jugador', 'Irak'),
  ('IRQ13', 'Irak - Foto del equipo', 'Irak'),
  ('IRQ14', 'Irak - Jugador', 'Irak'),
  ('IRQ15', 'Irak - Jugador', 'Irak'),
  ('IRQ16', 'Irak - Jugador', 'Irak'),
  ('IRQ17', 'Irak - Jugador', 'Irak'),
  ('IRQ18', 'Irak - Jugador', 'Irak'),
  ('IRQ19', 'Irak - Jugador', 'Irak'),
  ('IRQ20', 'Irak - Jugador', 'Irak'),
  ('JOR1', 'Jordania - Escudo (FOIL)', 'Jordania'),
  ('JOR2', 'Jordania - Jugador', 'Jordania'),
  ('JOR3', 'Jordania - Jugador', 'Jordania'),
  ('JOR4', 'Jordania - Jugador', 'Jordania'),
  ('JOR5', 'Jordania - Jugador', 'Jordania'),
  ('JOR6', 'Jordania - Jugador', 'Jordania'),
  ('JOR7', 'Jordania - Jugador', 'Jordania'),
  ('JOR8', 'Jordania - Jugador', 'Jordania'),
  ('JOR9', 'Jordania - Jugador', 'Jordania'),
  ('JOR10', 'Jordania - Jugador', 'Jordania'),
  ('JOR11', 'Jordania - Jugador', 'Jordania'),
  ('JOR12', 'Jordania - Jugador', 'Jordania'),
  ('JOR13', 'Jordania - Foto del equipo', 'Jordania'),
  ('JOR14', 'Jordania - Jugador', 'Jordania'),
  ('JOR15', 'Jordania - Jugador', 'Jordania'),
  ('JOR16', 'Jordania - Jugador', 'Jordania'),
  ('JOR17', 'Jordania - Jugador', 'Jordania'),
  ('JOR18', 'Jordania - Jugador', 'Jordania'),
  ('JOR19', 'Jordania - Jugador', 'Jordania'),
  ('JOR20', 'Jordania - Jugador', 'Jordania'),
  ('JPN1', 'Japón - Escudo (FOIL)', 'Japón'),
  ('JPN2', 'Japón - Jugador', 'Japón'),
  ('JPN3', 'Japón - Jugador', 'Japón'),
  ('JPN4', 'Japón - Jugador', 'Japón'),
  ('JPN5', 'Japón - Jugador', 'Japón'),
  ('JPN6', 'Japón - Jugador', 'Japón'),
  ('JPN7', 'Japón - Jugador', 'Japón'),
  ('JPN8', 'Japón - Jugador', 'Japón'),
  ('JPN9', 'Japón - Jugador', 'Japón'),
  ('JPN10', 'Japón - Jugador', 'Japón'),
  ('JPN11', 'Japón - Jugador', 'Japón'),
  ('JPN12', 'Japón - Jugador', 'Japón'),
  ('JPN13', 'Japón - Foto del equipo', 'Japón'),
  ('JPN14', 'Japón - Jugador', 'Japón'),
  ('JPN15', 'Japón - Jugador', 'Japón'),
  ('JPN16', 'Japón - Jugador', 'Japón'),
  ('JPN17', 'Japón - Jugador', 'Japón'),
  ('JPN18', 'Japón - Jugador', 'Japón'),
  ('JPN19', 'Japón - Jugador', 'Japón'),
  ('JPN20', 'Japón - Jugador', 'Japón'),
  ('KOR1', 'Corea del Sur - Escudo (FOIL)', 'Corea del Sur'),
  ('KOR2', 'Corea del Sur - Jugador', 'Corea del Sur'),
  ('KOR3', 'Corea del Sur - Jugador', 'Corea del Sur'),
  ('KOR4', 'Corea del Sur - Jugador', 'Corea del Sur'),
  ('KOR5', 'Corea del Sur - Jugador', 'Corea del Sur'),
  ('KOR6', 'Corea del Sur - Jugador', 'Corea del Sur'),
  ('KOR7', 'Corea del Sur - Jugador', 'Corea del Sur'),
  ('KOR8', 'Corea del Sur - Jugador', 'Corea del Sur'),
  ('KOR9', 'Corea del Sur - Jugador', 'Corea del Sur'),
  ('KOR10', 'Corea del Sur - Jugador', 'Corea del Sur'),
  ('KOR11', 'Corea del Sur - Jugador', 'Corea del Sur'),
  ('KOR12', 'Corea del Sur - Jugador', 'Corea del Sur'),
  ('KOR13', 'Corea del Sur - Foto del equipo', 'Corea del Sur'),
  ('KOR14', 'Corea del Sur - Jugador', 'Corea del Sur'),
  ('KOR15', 'Corea del Sur - Jugador', 'Corea del Sur'),
  ('KOR16', 'Corea del Sur - Jugador', 'Corea del Sur'),
  ('KOR17', 'Corea del Sur - Jugador', 'Corea del Sur'),
  ('KOR18', 'Corea del Sur - Jugador', 'Corea del Sur'),
  ('KOR19', 'Corea del Sur - Jugador', 'Corea del Sur'),
  ('KOR20', 'Corea del Sur - Jugador', 'Corea del Sur'),
  ('KSA1', 'Arabia Saudita - Escudo (FOIL)', 'Arabia Saudita'),
  ('KSA2', 'Arabia Saudita - Jugador', 'Arabia Saudita'),
  ('KSA3', 'Arabia Saudita - Jugador', 'Arabia Saudita'),
  ('KSA4', 'Arabia Saudita - Jugador', 'Arabia Saudita'),
  ('KSA5', 'Arabia Saudita - Jugador', 'Arabia Saudita'),
  ('KSA6', 'Arabia Saudita - Jugador', 'Arabia Saudita'),
  ('KSA7', 'Arabia Saudita - Jugador', 'Arabia Saudita'),
  ('KSA8', 'Arabia Saudita - Jugador', 'Arabia Saudita'),
  ('KSA9', 'Arabia Saudita - Jugador', 'Arabia Saudita'),
  ('KSA10', 'Arabia Saudita - Jugador', 'Arabia Saudita'),
  ('KSA11', 'Arabia Saudita - Jugador', 'Arabia Saudita'),
  ('KSA12', 'Arabia Saudita - Jugador', 'Arabia Saudita'),
  ('KSA13', 'Arabia Saudita - Foto del equipo', 'Arabia Saudita'),
  ('KSA14', 'Arabia Saudita - Jugador', 'Arabia Saudita'),
  ('KSA15', 'Arabia Saudita - Jugador', 'Arabia Saudita'),
  ('KSA16', 'Arabia Saudita - Jugador', 'Arabia Saudita'),
  ('KSA17', 'Arabia Saudita - Jugador', 'Arabia Saudita'),
  ('KSA18', 'Arabia Saudita - Jugador', 'Arabia Saudita'),
  ('KSA19', 'Arabia Saudita - Jugador', 'Arabia Saudita'),
  ('KSA20', 'Arabia Saudita - Jugador', 'Arabia Saudita'),
  ('MAR1', 'Marruecos - Escudo (FOIL)', 'Marruecos'),
  ('MAR2', 'Marruecos - Jugador', 'Marruecos'),
  ('MAR3', 'Marruecos - Jugador', 'Marruecos'),
  ('MAR4', 'Marruecos - Jugador', 'Marruecos'),
  ('MAR5', 'Marruecos - Jugador', 'Marruecos'),
  ('MAR6', 'Marruecos - Jugador', 'Marruecos'),
  ('MAR7', 'Marruecos - Jugador', 'Marruecos'),
  ('MAR8', 'Marruecos - Jugador', 'Marruecos'),
  ('MAR9', 'Marruecos - Jugador', 'Marruecos'),
  ('MAR10', 'Marruecos - Jugador', 'Marruecos'),
  ('MAR11', 'Marruecos - Jugador', 'Marruecos'),
  ('MAR12', 'Marruecos - Jugador', 'Marruecos'),
  ('MAR13', 'Marruecos - Foto del equipo', 'Marruecos'),
  ('MAR14', 'Marruecos - Jugador', 'Marruecos'),
  ('MAR15', 'Marruecos - Jugador', 'Marruecos'),
  ('MAR16', 'Marruecos - Jugador', 'Marruecos'),
  ('MAR17', 'Marruecos - Jugador', 'Marruecos'),
  ('MAR18', 'Marruecos - Jugador', 'Marruecos'),
  ('MAR19', 'Marruecos - Jugador', 'Marruecos'),
  ('MAR20', 'Marruecos - Jugador', 'Marruecos'),
  ('MEX1', 'México - Escudo (FOIL)', 'México'),
  ('MEX2', 'México - Jugador', 'México'),
  ('MEX3', 'México - Jugador', 'México'),
  ('MEX4', 'México - Jugador', 'México'),
  ('MEX5', 'México - Jugador', 'México'),
  ('MEX6', 'México - Jugador', 'México'),
  ('MEX7', 'México - Jugador', 'México'),
  ('MEX8', 'México - Jugador', 'México'),
  ('MEX9', 'México - Jugador', 'México'),
  ('MEX10', 'México - Jugador', 'México'),
  ('MEX11', 'México - Jugador', 'México'),
  ('MEX12', 'México - Jugador', 'México'),
  ('MEX13', 'México - Foto del equipo', 'México'),
  ('MEX14', 'México - Jugador', 'México'),
  ('MEX15', 'México - Jugador', 'México'),
  ('MEX16', 'México - Jugador', 'México'),
  ('MEX17', 'México - Jugador', 'México'),
  ('MEX18', 'México - Jugador', 'México'),
  ('MEX19', 'México - Jugador', 'México'),
  ('MEX20', 'México - Jugador', 'México'),
  ('NED1', 'Países Bajos - Escudo (FOIL)', 'Países Bajos'),
  ('NED2', 'Países Bajos - Jugador', 'Países Bajos'),
  ('NED3', 'Países Bajos - Jugador', 'Países Bajos'),
  ('NED4', 'Países Bajos - Jugador', 'Países Bajos'),
  ('NED5', 'Países Bajos - Jugador', 'Países Bajos'),
  ('NED6', 'Países Bajos - Jugador', 'Países Bajos'),
  ('NED7', 'Países Bajos - Jugador', 'Países Bajos'),
  ('NED8', 'Países Bajos - Jugador', 'Países Bajos'),
  ('NED9', 'Países Bajos - Jugador', 'Países Bajos'),
  ('NED10', 'Países Bajos - Jugador', 'Países Bajos'),
  ('NED11', 'Países Bajos - Jugador', 'Países Bajos'),
  ('NED12', 'Países Bajos - Jugador', 'Países Bajos'),
  ('NED13', 'Países Bajos - Foto del equipo', 'Países Bajos'),
  ('NED14', 'Países Bajos - Jugador', 'Países Bajos'),
  ('NED15', 'Países Bajos - Jugador', 'Países Bajos'),
  ('NED16', 'Países Bajos - Jugador', 'Países Bajos'),
  ('NED17', 'Países Bajos - Jugador', 'Países Bajos'),
  ('NED18', 'Países Bajos - Jugador', 'Países Bajos'),
  ('NED19', 'Países Bajos - Jugador', 'Países Bajos'),
  ('NED20', 'Países Bajos - Jugador', 'Países Bajos'),
  ('NOR1', 'Noruega - Escudo (FOIL)', 'Noruega'),
  ('NOR2', 'Noruega - Jugador', 'Noruega'),
  ('NOR3', 'Noruega - Jugador', 'Noruega'),
  ('NOR4', 'Noruega - Jugador', 'Noruega'),
  ('NOR5', 'Noruega - Jugador', 'Noruega'),
  ('NOR6', 'Noruega - Jugador', 'Noruega'),
  ('NOR7', 'Noruega - Jugador', 'Noruega'),
  ('NOR8', 'Noruega - Jugador', 'Noruega'),
  ('NOR9', 'Noruega - Jugador', 'Noruega'),
  ('NOR10', 'Noruega - Jugador', 'Noruega'),
  ('NOR11', 'Noruega - Jugador', 'Noruega'),
  ('NOR12', 'Noruega - Jugador', 'Noruega'),
  ('NOR13', 'Noruega - Foto del equipo', 'Noruega'),
  ('NOR14', 'Noruega - Jugador', 'Noruega'),
  ('NOR15', 'Noruega - Jugador', 'Noruega'),
  ('NOR16', 'Noruega - Jugador', 'Noruega'),
  ('NOR17', 'Noruega - Jugador', 'Noruega'),
  ('NOR18', 'Noruega - Jugador', 'Noruega'),
  ('NOR19', 'Noruega - Jugador', 'Noruega'),
  ('NOR20', 'Noruega - Jugador', 'Noruega'),
  ('NZL1', 'Nueva Zelanda - Escudo (FOIL)', 'Nueva Zelanda'),
  ('NZL2', 'Nueva Zelanda - Jugador', 'Nueva Zelanda'),
  ('NZL3', 'Nueva Zelanda - Jugador', 'Nueva Zelanda'),
  ('NZL4', 'Nueva Zelanda - Jugador', 'Nueva Zelanda'),
  ('NZL5', 'Nueva Zelanda - Jugador', 'Nueva Zelanda'),
  ('NZL6', 'Nueva Zelanda - Jugador', 'Nueva Zelanda'),
  ('NZL7', 'Nueva Zelanda - Jugador', 'Nueva Zelanda'),
  ('NZL8', 'Nueva Zelanda - Jugador', 'Nueva Zelanda'),
  ('NZL9', 'Nueva Zelanda - Jugador', 'Nueva Zelanda'),
  ('NZL10', 'Nueva Zelanda - Jugador', 'Nueva Zelanda'),
  ('NZL11', 'Nueva Zelanda - Jugador', 'Nueva Zelanda'),
  ('NZL12', 'Nueva Zelanda - Jugador', 'Nueva Zelanda'),
  ('NZL13', 'Nueva Zelanda - Foto del equipo', 'Nueva Zelanda'),
  ('NZL14', 'Nueva Zelanda - Jugador', 'Nueva Zelanda'),
  ('NZL15', 'Nueva Zelanda - Jugador', 'Nueva Zelanda'),
  ('NZL16', 'Nueva Zelanda - Jugador', 'Nueva Zelanda'),
  ('NZL17', 'Nueva Zelanda - Jugador', 'Nueva Zelanda'),
  ('NZL18', 'Nueva Zelanda - Jugador', 'Nueva Zelanda'),
  ('NZL19', 'Nueva Zelanda - Jugador', 'Nueva Zelanda'),
  ('NZL20', 'Nueva Zelanda - Jugador', 'Nueva Zelanda'),
  ('PAN1', 'Panamá - Escudo (FOIL)', 'Panamá'),
  ('PAN2', 'Panamá - Jugador', 'Panamá'),
  ('PAN3', 'Panamá - Jugador', 'Panamá'),
  ('PAN4', 'Panamá - Jugador', 'Panamá'),
  ('PAN5', 'Panamá - Jugador', 'Panamá'),
  ('PAN6', 'Panamá - Jugador', 'Panamá'),
  ('PAN7', 'Panamá - Jugador', 'Panamá'),
  ('PAN8', 'Panamá - Jugador', 'Panamá'),
  ('PAN9', 'Panamá - Jugador', 'Panamá'),
  ('PAN10', 'Panamá - Jugador', 'Panamá'),
  ('PAN11', 'Panamá - Jugador', 'Panamá'),
  ('PAN12', 'Panamá - Jugador', 'Panamá'),
  ('PAN13', 'Panamá - Foto del equipo', 'Panamá'),
  ('PAN14', 'Panamá - Jugador', 'Panamá'),
  ('PAN15', 'Panamá - Jugador', 'Panamá'),
  ('PAN16', 'Panamá - Jugador', 'Panamá'),
  ('PAN17', 'Panamá - Jugador', 'Panamá'),
  ('PAN18', 'Panamá - Jugador', 'Panamá'),
  ('PAN19', 'Panamá - Jugador', 'Panamá'),
  ('PAN20', 'Panamá - Jugador', 'Panamá'),
  ('PAR1', 'Paraguay - Escudo (FOIL)', 'Paraguay'),
  ('PAR2', 'Paraguay - Jugador', 'Paraguay'),
  ('PAR3', 'Paraguay - Jugador', 'Paraguay'),
  ('PAR4', 'Paraguay - Jugador', 'Paraguay'),
  ('PAR5', 'Paraguay - Jugador', 'Paraguay'),
  ('PAR6', 'Paraguay - Jugador', 'Paraguay'),
  ('PAR7', 'Paraguay - Jugador', 'Paraguay'),
  ('PAR8', 'Paraguay - Jugador', 'Paraguay'),
  ('PAR9', 'Paraguay - Jugador', 'Paraguay'),
  ('PAR10', 'Paraguay - Jugador', 'Paraguay'),
  ('PAR11', 'Paraguay - Jugador', 'Paraguay'),
  ('PAR12', 'Paraguay - Jugador', 'Paraguay'),
  ('PAR13', 'Paraguay - Foto del equipo', 'Paraguay'),
  ('PAR14', 'Paraguay - Jugador', 'Paraguay'),
  ('PAR15', 'Paraguay - Jugador', 'Paraguay'),
  ('PAR16', 'Paraguay - Jugador', 'Paraguay'),
  ('PAR17', 'Paraguay - Jugador', 'Paraguay'),
  ('PAR18', 'Paraguay - Jugador', 'Paraguay'),
  ('PAR19', 'Paraguay - Jugador', 'Paraguay'),
  ('PAR20', 'Paraguay - Jugador', 'Paraguay'),
  ('POR1', 'Portugal - Escudo (FOIL)', 'Portugal'),
  ('POR2', 'Portugal - Jugador', 'Portugal'),
  ('POR3', 'Portugal - Jugador', 'Portugal'),
  ('POR4', 'Portugal - Jugador', 'Portugal'),
  ('POR5', 'Portugal - Jugador', 'Portugal'),
  ('POR6', 'Portugal - Jugador', 'Portugal'),
  ('POR7', 'Portugal - Jugador', 'Portugal'),
  ('POR8', 'Portugal - Jugador', 'Portugal'),
  ('POR9', 'Portugal - Jugador', 'Portugal'),
  ('POR10', 'Portugal - Jugador', 'Portugal'),
  ('POR11', 'Portugal - Jugador', 'Portugal'),
  ('POR12', 'Portugal - Jugador', 'Portugal'),
  ('POR13', 'Portugal - Foto del equipo', 'Portugal'),
  ('POR14', 'Portugal - Jugador', 'Portugal'),
  ('POR15', 'Portugal - Jugador', 'Portugal'),
  ('POR16', 'Portugal - Jugador', 'Portugal'),
  ('POR17', 'Portugal - Jugador', 'Portugal'),
  ('POR18', 'Portugal - Jugador', 'Portugal'),
  ('POR19', 'Portugal - Jugador', 'Portugal'),
  ('POR20', 'Portugal - Jugador', 'Portugal'),
  ('QAT1', 'Qatar - Escudo (FOIL)', 'Qatar'),
  ('QAT2', 'Qatar - Jugador', 'Qatar'),
  ('QAT3', 'Qatar - Jugador', 'Qatar'),
  ('QAT4', 'Qatar - Jugador', 'Qatar'),
  ('QAT5', 'Qatar - Jugador', 'Qatar'),
  ('QAT6', 'Qatar - Jugador', 'Qatar'),
  ('QAT7', 'Qatar - Jugador', 'Qatar'),
  ('QAT8', 'Qatar - Jugador', 'Qatar'),
  ('QAT9', 'Qatar - Jugador', 'Qatar'),
  ('QAT10', 'Qatar - Jugador', 'Qatar'),
  ('QAT11', 'Qatar - Jugador', 'Qatar'),
  ('QAT12', 'Qatar - Jugador', 'Qatar'),
  ('QAT13', 'Qatar - Foto del equipo', 'Qatar'),
  ('QAT14', 'Qatar - Jugador', 'Qatar'),
  ('QAT15', 'Qatar - Jugador', 'Qatar'),
  ('QAT16', 'Qatar - Jugador', 'Qatar'),
  ('QAT17', 'Qatar - Jugador', 'Qatar'),
  ('QAT18', 'Qatar - Jugador', 'Qatar'),
  ('QAT19', 'Qatar - Jugador', 'Qatar'),
  ('QAT20', 'Qatar - Jugador', 'Qatar'),
  ('RSA1', 'Sudáfrica - Escudo (FOIL)', 'Sudáfrica'),
  ('RSA2', 'Sudáfrica - Jugador', 'Sudáfrica'),
  ('RSA3', 'Sudáfrica - Jugador', 'Sudáfrica'),
  ('RSA4', 'Sudáfrica - Jugador', 'Sudáfrica'),
  ('RSA5', 'Sudáfrica - Jugador', 'Sudáfrica'),
  ('RSA6', 'Sudáfrica - Jugador', 'Sudáfrica'),
  ('RSA7', 'Sudáfrica - Jugador', 'Sudáfrica'),
  ('RSA8', 'Sudáfrica - Jugador', 'Sudáfrica'),
  ('RSA9', 'Sudáfrica - Jugador', 'Sudáfrica'),
  ('RSA10', 'Sudáfrica - Jugador', 'Sudáfrica'),
  ('RSA11', 'Sudáfrica - Jugador', 'Sudáfrica'),
  ('RSA12', 'Sudáfrica - Jugador', 'Sudáfrica'),
  ('RSA13', 'Sudáfrica - Foto del equipo', 'Sudáfrica'),
  ('RSA14', 'Sudáfrica - Jugador', 'Sudáfrica'),
  ('RSA15', 'Sudáfrica - Jugador', 'Sudáfrica'),
  ('RSA16', 'Sudáfrica - Jugador', 'Sudáfrica'),
  ('RSA17', 'Sudáfrica - Jugador', 'Sudáfrica'),
  ('RSA18', 'Sudáfrica - Jugador', 'Sudáfrica'),
  ('RSA19', 'Sudáfrica - Jugador', 'Sudáfrica'),
  ('RSA20', 'Sudáfrica - Jugador', 'Sudáfrica'),
  ('SCO1', 'Escocia - Escudo (FOIL)', 'Escocia'),
  ('SCO2', 'Escocia - Jugador', 'Escocia'),
  ('SCO3', 'Escocia - Jugador', 'Escocia'),
  ('SCO4', 'Escocia - Jugador', 'Escocia'),
  ('SCO5', 'Escocia - Jugador', 'Escocia'),
  ('SCO6', 'Escocia - Jugador', 'Escocia'),
  ('SCO7', 'Escocia - Jugador', 'Escocia'),
  ('SCO8', 'Escocia - Jugador', 'Escocia'),
  ('SCO9', 'Escocia - Jugador', 'Escocia'),
  ('SCO10', 'Escocia - Jugador', 'Escocia'),
  ('SCO11', 'Escocia - Jugador', 'Escocia'),
  ('SCO12', 'Escocia - Jugador', 'Escocia'),
  ('SCO13', 'Escocia - Foto del equipo', 'Escocia'),
  ('SCO14', 'Escocia - Jugador', 'Escocia'),
  ('SCO15', 'Escocia - Jugador', 'Escocia'),
  ('SCO16', 'Escocia - Jugador', 'Escocia'),
  ('SCO17', 'Escocia - Jugador', 'Escocia'),
  ('SCO18', 'Escocia - Jugador', 'Escocia'),
  ('SCO19', 'Escocia - Jugador', 'Escocia'),
  ('SCO20', 'Escocia - Jugador', 'Escocia'),
  ('SEN1', 'Senegal - Escudo (FOIL)', 'Senegal'),
  ('SEN2', 'Senegal - Jugador', 'Senegal'),
  ('SEN3', 'Senegal - Jugador', 'Senegal'),
  ('SEN4', 'Senegal - Jugador', 'Senegal'),
  ('SEN5', 'Senegal - Jugador', 'Senegal'),
  ('SEN6', 'Senegal - Jugador', 'Senegal'),
  ('SEN7', 'Senegal - Jugador', 'Senegal'),
  ('SEN8', 'Senegal - Jugador', 'Senegal'),
  ('SEN9', 'Senegal - Jugador', 'Senegal'),
  ('SEN10', 'Senegal - Jugador', 'Senegal'),
  ('SEN11', 'Senegal - Jugador', 'Senegal'),
  ('SEN12', 'Senegal - Jugador', 'Senegal'),
  ('SEN13', 'Senegal - Foto del equipo', 'Senegal'),
  ('SEN14', 'Senegal - Jugador', 'Senegal'),
  ('SEN15', 'Senegal - Jugador', 'Senegal'),
  ('SEN16', 'Senegal - Jugador', 'Senegal'),
  ('SEN17', 'Senegal - Jugador', 'Senegal'),
  ('SEN18', 'Senegal - Jugador', 'Senegal'),
  ('SEN19', 'Senegal - Jugador', 'Senegal'),
  ('SEN20', 'Senegal - Jugador', 'Senegal'),
  ('SUI1', 'Suiza - Escudo (FOIL)', 'Suiza'),
  ('SUI2', 'Suiza - Jugador', 'Suiza'),
  ('SUI3', 'Suiza - Jugador', 'Suiza'),
  ('SUI4', 'Suiza - Jugador', 'Suiza'),
  ('SUI5', 'Suiza - Jugador', 'Suiza'),
  ('SUI6', 'Suiza - Jugador', 'Suiza'),
  ('SUI7', 'Suiza - Jugador', 'Suiza'),
  ('SUI8', 'Suiza - Jugador', 'Suiza'),
  ('SUI9', 'Suiza - Jugador', 'Suiza'),
  ('SUI10', 'Suiza - Jugador', 'Suiza'),
  ('SUI11', 'Suiza - Jugador', 'Suiza'),
  ('SUI12', 'Suiza - Jugador', 'Suiza'),
  ('SUI13', 'Suiza - Foto del equipo', 'Suiza'),
  ('SUI14', 'Suiza - Jugador', 'Suiza'),
  ('SUI15', 'Suiza - Jugador', 'Suiza'),
  ('SUI16', 'Suiza - Jugador', 'Suiza'),
  ('SUI17', 'Suiza - Jugador', 'Suiza'),
  ('SUI18', 'Suiza - Jugador', 'Suiza'),
  ('SUI19', 'Suiza - Jugador', 'Suiza'),
  ('SUI20', 'Suiza - Jugador', 'Suiza'),
  ('SWE1', 'Suecia - Escudo (FOIL)', 'Suecia'),
  ('SWE2', 'Suecia - Jugador', 'Suecia'),
  ('SWE3', 'Suecia - Jugador', 'Suecia'),
  ('SWE4', 'Suecia - Jugador', 'Suecia'),
  ('SWE5', 'Suecia - Jugador', 'Suecia'),
  ('SWE6', 'Suecia - Jugador', 'Suecia'),
  ('SWE7', 'Suecia - Jugador', 'Suecia'),
  ('SWE8', 'Suecia - Jugador', 'Suecia'),
  ('SWE9', 'Suecia - Jugador', 'Suecia'),
  ('SWE10', 'Suecia - Jugador', 'Suecia'),
  ('SWE11', 'Suecia - Jugador', 'Suecia'),
  ('SWE12', 'Suecia - Jugador', 'Suecia'),
  ('SWE13', 'Suecia - Foto del equipo', 'Suecia'),
  ('SWE14', 'Suecia - Jugador', 'Suecia'),
  ('SWE15', 'Suecia - Jugador', 'Suecia'),
  ('SWE16', 'Suecia - Jugador', 'Suecia'),
  ('SWE17', 'Suecia - Jugador', 'Suecia'),
  ('SWE18', 'Suecia - Jugador', 'Suecia'),
  ('SWE19', 'Suecia - Jugador', 'Suecia'),
  ('SWE20', 'Suecia - Jugador', 'Suecia'),
  ('TUN1', 'Túnez - Escudo (FOIL)', 'Túnez'),
  ('TUN2', 'Túnez - Jugador', 'Túnez'),
  ('TUN3', 'Túnez - Jugador', 'Túnez'),
  ('TUN4', 'Túnez - Jugador', 'Túnez'),
  ('TUN5', 'Túnez - Jugador', 'Túnez'),
  ('TUN6', 'Túnez - Jugador', 'Túnez'),
  ('TUN7', 'Túnez - Jugador', 'Túnez'),
  ('TUN8', 'Túnez - Jugador', 'Túnez'),
  ('TUN9', 'Túnez - Jugador', 'Túnez'),
  ('TUN10', 'Túnez - Jugador', 'Túnez'),
  ('TUN11', 'Túnez - Jugador', 'Túnez'),
  ('TUN12', 'Túnez - Jugador', 'Túnez'),
  ('TUN13', 'Túnez - Foto del equipo', 'Túnez'),
  ('TUN14', 'Túnez - Jugador', 'Túnez'),
  ('TUN15', 'Túnez - Jugador', 'Túnez'),
  ('TUN16', 'Túnez - Jugador', 'Túnez'),
  ('TUN17', 'Túnez - Jugador', 'Túnez'),
  ('TUN18', 'Túnez - Jugador', 'Túnez'),
  ('TUN19', 'Túnez - Jugador', 'Túnez'),
  ('TUN20', 'Túnez - Jugador', 'Túnez'),
  ('TUR1', 'Turquía - Escudo (FOIL)', 'Turquía'),
  ('TUR2', 'Turquía - Jugador', 'Turquía'),
  ('TUR3', 'Turquía - Jugador', 'Turquía'),
  ('TUR4', 'Turquía - Jugador', 'Turquía'),
  ('TUR5', 'Turquía - Jugador', 'Turquía'),
  ('TUR6', 'Turquía - Jugador', 'Turquía'),
  ('TUR7', 'Turquía - Jugador', 'Turquía'),
  ('TUR8', 'Turquía - Jugador', 'Turquía'),
  ('TUR9', 'Turquía - Jugador', 'Turquía'),
  ('TUR10', 'Turquía - Jugador', 'Turquía'),
  ('TUR11', 'Turquía - Jugador', 'Turquía'),
  ('TUR12', 'Turquía - Jugador', 'Turquía'),
  ('TUR13', 'Turquía - Foto del equipo', 'Turquía'),
  ('TUR14', 'Turquía - Jugador', 'Turquía'),
  ('TUR15', 'Turquía - Jugador', 'Turquía'),
  ('TUR16', 'Turquía - Jugador', 'Turquía'),
  ('TUR17', 'Turquía - Jugador', 'Turquía'),
  ('TUR18', 'Turquía - Jugador', 'Turquía'),
  ('TUR19', 'Turquía - Jugador', 'Turquía'),
  ('TUR20', 'Turquía - Jugador', 'Turquía'),
  ('URU1', 'Uruguay - Escudo (FOIL)', 'Uruguay'),
  ('URU2', 'Uruguay - Jugador', 'Uruguay'),
  ('URU3', 'Uruguay - Jugador', 'Uruguay'),
  ('URU4', 'Uruguay - Jugador', 'Uruguay'),
  ('URU5', 'Uruguay - Jugador', 'Uruguay'),
  ('URU6', 'Uruguay - Jugador', 'Uruguay'),
  ('URU7', 'Uruguay - Jugador', 'Uruguay'),
  ('URU8', 'Uruguay - Jugador', 'Uruguay'),
  ('URU9', 'Uruguay - Jugador', 'Uruguay'),
  ('URU10', 'Uruguay - Jugador', 'Uruguay'),
  ('URU11', 'Uruguay - Jugador', 'Uruguay'),
  ('URU12', 'Uruguay - Jugador', 'Uruguay'),
  ('URU13', 'Uruguay - Foto del equipo', 'Uruguay'),
  ('URU14', 'Uruguay - Jugador', 'Uruguay'),
  ('URU15', 'Uruguay - Jugador', 'Uruguay'),
  ('URU16', 'Uruguay - Jugador', 'Uruguay'),
  ('URU17', 'Uruguay - Jugador', 'Uruguay'),
  ('URU18', 'Uruguay - Jugador', 'Uruguay'),
  ('URU19', 'Uruguay - Jugador', 'Uruguay'),
  ('URU20', 'Uruguay - Jugador', 'Uruguay'),
  ('USA1', 'Estados Unidos - Escudo (FOIL)', 'Estados Unidos'),
  ('USA2', 'Estados Unidos - Jugador', 'Estados Unidos'),
  ('USA3', 'Estados Unidos - Jugador', 'Estados Unidos'),
  ('USA4', 'Estados Unidos - Jugador', 'Estados Unidos'),
  ('USA5', 'Estados Unidos - Jugador', 'Estados Unidos'),
  ('USA6', 'Estados Unidos - Jugador', 'Estados Unidos'),
  ('USA7', 'Estados Unidos - Jugador', 'Estados Unidos'),
  ('USA8', 'Estados Unidos - Jugador', 'Estados Unidos'),
  ('USA9', 'Estados Unidos - Jugador', 'Estados Unidos'),
  ('USA10', 'Estados Unidos - Jugador', 'Estados Unidos'),
  ('USA11', 'Estados Unidos - Jugador', 'Estados Unidos'),
  ('USA12', 'Estados Unidos - Jugador', 'Estados Unidos'),
  ('USA13', 'Estados Unidos - Foto del equipo', 'Estados Unidos'),
  ('USA14', 'Estados Unidos - Jugador', 'Estados Unidos'),
  ('USA15', 'Estados Unidos - Jugador', 'Estados Unidos'),
  ('USA16', 'Estados Unidos - Jugador', 'Estados Unidos'),
  ('USA17', 'Estados Unidos - Jugador', 'Estados Unidos'),
  ('USA18', 'Estados Unidos - Jugador', 'Estados Unidos'),
  ('USA19', 'Estados Unidos - Jugador', 'Estados Unidos'),
  ('USA20', 'Estados Unidos - Jugador', 'Estados Unidos'),
  ('UZB1', 'Uzbekistán - Escudo (FOIL)', 'Uzbekistán'),
  ('UZB2', 'Uzbekistán - Jugador', 'Uzbekistán'),
  ('UZB3', 'Uzbekistán - Jugador', 'Uzbekistán'),
  ('UZB4', 'Uzbekistán - Jugador', 'Uzbekistán'),
  ('UZB5', 'Uzbekistán - Jugador', 'Uzbekistán'),
  ('UZB6', 'Uzbekistán - Jugador', 'Uzbekistán'),
  ('UZB7', 'Uzbekistán - Jugador', 'Uzbekistán'),
  ('UZB8', 'Uzbekistán - Jugador', 'Uzbekistán'),
  ('UZB9', 'Uzbekistán - Jugador', 'Uzbekistán'),
  ('UZB10', 'Uzbekistán - Jugador', 'Uzbekistán'),
  ('UZB11', 'Uzbekistán - Jugador', 'Uzbekistán'),
  ('UZB12', 'Uzbekistán - Jugador', 'Uzbekistán'),
  ('UZB13', 'Uzbekistán - Foto del equipo', 'Uzbekistán'),
  ('UZB14', 'Uzbekistán - Jugador', 'Uzbekistán'),
  ('UZB15', 'Uzbekistán - Jugador', 'Uzbekistán'),
  ('UZB16', 'Uzbekistán - Jugador', 'Uzbekistán'),
  ('UZB17', 'Uzbekistán - Jugador', 'Uzbekistán'),
  ('UZB18', 'Uzbekistán - Jugador', 'Uzbekistán'),
  ('UZB19', 'Uzbekistán - Jugador', 'Uzbekistán'),
  ('UZB20', 'Uzbekistán - Jugador', 'Uzbekistán');

